on:
  push:
    branches: [main, feature/github-actions]
  pull_request:
name: Flatbuild
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    #container:
    #  image: bilelmoussaoui/flatpak-github-actions:gnome-3.38
    #  options: --privileged
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder
        flatpak --user remote-add --if-not-exists --from flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak --user install -y --noninteractive flathub org.gnome.Platform//3.38
    - uses: actions/checkout@v2
    - name: Build flatpak package
      run: |
        mkdir repo
        cd flatpak
        ./flatbuild.sh
        ls -l
#    - name: Build flatpak package
#      uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
#      with:
#        bundle: gneelight.flatpak
#        manifest-path: flatpak/me.vinsce.Gneelight.json
#        cache-key: flatpak-builder-${{ github.sha }}
    - run: ls -l
    # - uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: gneelignt.flatpak