on:
  push:
    branches: [main, feature/github-actions]
  pull_request:
name: Flatbuild
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-3.38
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: gneelight.flatpak
        manifest-path: flatpack/gneelight.flatpak
        cache-key: flatpak-builder-${{ github.sha }}