on:
  push:
    branches: [main, feature/github-actions]
    tags:
      - v.*
  pull_request:
name: Flatbuild
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder
        flatpak remote-add --user --if-not-exists --from flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak --user install -y flathub org.gnome.Platform//40
        flatpak --user install -y flathub org.gnome.Sdk//40
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build flatpak package
      run: |
        mkdir repo
        cd flatpak
        ./flatbuild.sh
        ls -l
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          flatpak/gneelignt.flatpak
          gneelignt.flatpak